### ISSUE TITLE
Tweak Installation

### ISSUE THREAD

**Issue by josephwalden13** [4ppleCracker/RepositoryExplorer#3]
I think you forgot to add the code for 'Install Selected' :D. It's just a blank button. Also, I noticed that you only used the tweak installer for electra, but Tweak Installer auto detects whether or not the user is running Electra and works accross all jailbreaks :) Also, it seems to be running a new install process for each deb, whereas you could just call 'tic.exe install dont-update deb1 deb2 deb3 etc' to do it all in one go. I think this would also simplify the non tweak installer installations if you used tic for non-electra as well. ~~Finally it runs 'tic.exe' but you have 'tic.exe' in a folder called tics so it doesn't work.~~FIXED

I'll add these updates to my fork and submit a merge request :) 

Also nice tool btw :)

Also you've set the port to "root". This is my fault as in older versions of my tool data[1] was user, but I removed it because it's always 'root'. In my fork I've changed it to port.Text

**Comment by josephwalden13** [comment]
Also, nice tool btw :)

**Comment by josephwalden13** [comment]
Also you've set the port to "root". This is my fault as in older versions of my tool data[1] was user, but I removed it because it's always 'root'. In my fork I've changed it to port.Text

**Comment by nobbele** [comment]
Oh right, forgot to fix the current selected thing, will fix asap. Will also fix the location and user/port thing. 👍

**Comment by josephwalden13** [comment]
Also when the 'tic.exe' is executed it runs in the current directory, so you need to change the directory it executes in to 'tics'. You can do this temporarily using:

```
Environment.CurrentDirectory += "\\tics"; //temporary
string[] data = { host.Text, port.Text, password.Text };
File.WriteAllLines("settings", data);
Process.Start("tic.exe", "dont-update " + "install " + deb.FullName);
Environment.CurrentDirectory += "\\..\\"; //revert
```

The code also deletes 'settings', but regenerates a blank version when you launch the program if it doesn't exist? Is that intentional?

**Comment by nobbele** [comment]
> The code also deletes 'settings', but regenerates a blank version when you launch the program if it doesn't exist? Is that intentional?

I delete the settings every time because of security reasons, so your password isn't stored in plain text

**Comment by nobbele** [comment]
Everything here should be fixed in the latest commits
