### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by teefixx** [4ppleCracker/RepositoryExplorer#5]
Hi 
When I select "Add default Repo" I get an error message "unhandled exception", Type "System.Runtime.CompilerSerivices.ExtensionAttribute" at the Assembly "mscorlib, Version=4.0.0.0, Culture=neutral.

System: Windows 7x64

**Comment by nobbele** [comment]
I don't have enough info about the issue, try reinstalling, removing all .repo files and updating windows
